### ISSUE TITLE
Gradle does not work with Cordova/Intel XDK

### ISSUE THREAD

**Issue by Ami777** [blakgeek/cordova-plugin-supersonicads#1]
Hi,

when I try to build project with this plugin (which looks very nice & promising!) I get an error:
Error: Plugin Supersonic Ads Cordova Plugin cannot be added. The plugin contains Gradle scripts.

What can I do to bypass it?
I found this file:  cordova-plugin-supersonicads/src/android/supersonicads.gradle .
Can I manually run this file for example, to add it to my project?

Im using Intel XDK / Cordova.

Thank you in advance,
Jakub Król.

**Comment by blakgeek** [comment]
What version of Cordova are you using?

**Comment by blakgeek** [comment]
Can you also paste the full output when you try to build?

**Comment by Ami777** [comment]
Hi.

Im using Intel XDK and I think this might be the problem. Cordova CLI V 4.1.2.

Full output:
The build failed. An error occurred while building the application. Verify your build assets are correct and try again.
Build Log:
Building a Cordova 4.1.2 application.
The application name is "ssadstest"
The package name is "xdk.intel.blank.template"
Plugin "org.apache.cordova.device" (0.2.13) installed.
Plugin "org.apache.cordova.splashscreen" (0.3.5) installed.
Error: Plugin cordova-plugin-supersonicads cannot be added. The plugin contains Gradle scripts.

**Comment by Ami777** [comment]
I have tried Cordova CLI 5.1.1 now and get only this:

The build failed. An error occurred while building the application. Verify your build assets are correct and try again.
Build Log:
Building a Cordova 5.1.1 application.
The application name is "ssadstest"
The package name is "xdk.intel.blank.template"
Error: Plugin "cordova-plugin-supersonicads" failed to install.
Plugin "org.apache.cordova.device" (0.2.13) installed.
Plugin "org.apache.cordova.splashscreen" (0.3.5) installed.
